### ISSUE TITLE
JSON Input builder stucks

### ISSUE THREAD

**Issue by jguse** [requence/requence#4]
# Bug Report

## Title
JSON Input builder stucks

## Description
When building json schemas, the inputs stuck

## Steps to Reproduce
1. Services
2. create Service
3. edit the service to change the config
4. try to edit config

![image](https://github.com/user-attachments/assets/de7440cb-698e-43ba-9830-602da35028bc)

## Expected Behavior
Inputs can be changed

## Actual Behavior
Inputs can not be changed

## Possible Fixes
Set correct focus element

**Comment by Torsten85** [comment]
Fixed in `1.0.0-alpha.15`
