### ISSUE TITLE
Hover state on dropdown problem

### ISSUE THREAD

**Issue by jguse** [requence/requence#5]
# Bug Report

## Title
Hover state on dropdown problem

## Description
When hover over an dropdown option, the submenu flickers

## Steps to Reproduce
1. Edit service
2. select array

https://github.com/user-attachments/assets/4e039920-9f5e-4416-8a46-a30be1a6be86

## Expected Behavior
Submenu will appear

## Actual Behavior
Submenu flickers

**Comment by Torsten85** [comment]
Fixed in `1.0.0-alpha.15`
