### ISSUE TITLE
Configuration not fuflfilled

### ISSUE THREAD

**Issue by davecrosser91** [requence/requence#7]
# Bug Report
![Image](https://github.com/user-attachments/assets/6d747b84-7da1-406d-976d-af33d489cc9a)

## Title
Configuration not fulfilled

## Description
It shows that the configuration is not fulfillen eventhough it is.

## Steps to Reproduce
1.  Add configuration to a service with format string
2. choose service and enter a string

## Expected Behavior
No error message

## Actual Behavior
error message

## Possible Fixes
If you have any suggestions on what might be causing the issue or how to fix it, please include them here.

## Environment
- Operating System:
- Software Version:
- Hardware Specs:

## Additional Context
Add any other context about the problem here, such as the frequency of the bug, if it occurs only under specific conditions, or anything else that is relevant.

**Comment by Torsten85** [comment]
Fixed in `1.0.0-alpha.16`
