### ISSUE TITLE
JSON Input Builder Any of

### ISSUE THREAD

**Issue by davecrosser91** [requence/requence#8]
# Bug Report
![Image](https://github.com/user-attachments/assets/9012fe2e-6f60-412e-b5e3-e6af4158b083)

## Title
When selecting any of in the json builder I do not see an input field to add another value

## Description
The bug appeared in the JSON Builder component in a service

**Comment by Torsten85** [comment]
The UI was a little bit broken, but it's fixed in `1.0.0-alpha.17`. 

The Any Of Type makes a Union of other types. So there is no input field (as for object keys). 

Like _the property "goal" of my object can be of type string or number or boolean._
